config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'welcome#index'
  resources :articles
  resources :projects
  resources :contacts, only: [:new, :create]
  get '*path' => redirect('/')

end

app/models/article.rb
class Article < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message,   :validate => true
  attribute :nickname,  :captcha  => true

  def headers
    {
        :subject => 'Contact Form',
        :to => 'adamdebbagh@gmail.com',
        :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :find_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  def index
  @articles = Article.all.order('created_at DESC').paginate(page: params[:page], per_page:3)
  end
  def show
  end
  def new
  @article = Article.new
  end
  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to @article, notice: "Article successfully Saved"
    else
      render 'new', notice: "Article Failed to Save"
    end
  end
  def edit
  end
  def update
    if @article.update article_params
      redirect_to @article, notice: "Article successfully Updated"
    else
      render 'edit', notice: "Article Failed to Update"
    end
  end
  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :content, :slug)
  end

  def find_article
    @article = Article.friendly.find(params[:id])
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:error] = nil
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :find_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @projects = Project.all.order('created_at desc')
  end
  def show

  end
  def new
    @project = Project.new
  end
  def create
    @project = Project.new project_params
    if @project.save
      redirect_to @project, notice: 'Project successfully created'
    else
      render 'new', notice: 'Project was not created.Try again '
    end
  end
  def edit
  end
  def update
    if @project.update project_params
      redirect_to @project , notice: 'Project successfully updated'
    else
      render 'edit'
    end
  end
  def destroy
    @project.destroy
    redirect_to projects_path
  end

private
  def find_project
   @project = Project.friendly.find(params[:id])
  end
  def project_params
    params.require(:project).permit(:title, :description, :link, :slug)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @articles = Article.all.limit(3).order('created_at desc')
    @projects = Project.all.limit(3).order('created_at desc')

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  class HTMLwithPygments < Redcarpet::Render::HTML
    def block_code(code, language)
      Pygments.highlight(code, lexer: language)
    end
  end
  def markdown(content)
    renderer = HTMLwithPygments.new(hard_wrap: true, filter_html: true)
    options = {
        autolink: true,
        no_intra_emphasis: true,
        disable_indented_code_blocks: true,
        fenced_code_blocks: true,
        lax_html_blocks: true,
        strikethrough: true,
        superscript: true
    }
    Redcarpet::Markdown.new(renderer, options).render(content).html_safe
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_disqus.html.erb
<div id="disqus_thread"></div>
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES * * */
    var disqus_shortname = 'adamdebbagh';
    var disqus_identifier = '<%= @article.id%>';
    var disqus_title = '<%= @article.title%>';
    var disqus_url = '<%= url_for([@article, {only_path: false}]) %>';


    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
    <% if @article.errors.any? %>
        <h2><%= pluralize(@post.count,"error")%> prevented this article from saving:</h2>
        <ul>
          <% @article.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
          <% end %>
        </ul>
    <% end %>

    <%= f.label :title%><br>
    <%= f.text_field :title%>
    <br><br>
    <%= f.label :content, "Write you article here" %><br>
    <%= f.text_area :content %>
    <br><br>
    <%= f.submit %>
<% end%>

app/views/articles/edit.html.erb
<div class="wrapper_padding skinny_wrapper">
<h1 id="page_title">Edit Article</h1>
<%= render 'form'%>

app/views/articles/index.html.erb
<h1 id="page_title">Stuff i've written <br><br>
  <span class="new_button">
   <% if user_signed_in? %>
      <%= link_to 'New Article', new_article_path %>
   <% end %>
  </span>
</h1>
<div id="post_wrapper" class="skinny_wrapper">
  <% @articles.each do |article| %>
      <div class="post">
        <p class="date"><%= article.created_at.strftime('%A, %b %d')%></p>
        <h2><%= link_to article.title, article %></h2>
        <hr>
      </div>
  <% end%>
</div>
<%= will_paginate @articles %>

app/views/articles/new.html.erb
<div class="wrapper_padding skinny_wrapper">
    <h1 id="page_title">New Article</h1>
    <%=  render 'form' %>
</div>

app/views/articles/show.html.erb
<div id="post_show_content" class="skinny_wrapper wrapper_padding">
  <header>
    <p class="date"><%= @article.created_at.strftime( ' %A' ' %b' ' %d') %></p>
    <h1><%= @article.title %></h1>
    <hr>
  </header>

  <div id="content">
    <% author = ' By Adam Debbagh, Developer'%>
    <h6><%= author %></h6>
    <p><%= markdown @article.content %></p>
  </div>
  <% if user_signed_in? %>
      <div id="admin_links">
        <%= link_to 'edit', edit_article_path(@article) %>
        <%= link_to 'delete', article_path(@article), method: :delete, data: {
                                    confirm: "Are you sure you want to delete this post?"} %>
      </div>
  <% end %>
  <hr>

  <div id="share_box">
    <p>Share <%= @article.title %></p>
    <!-- Twitter -->
    <a onclick="javascript:window.open('http://twitter.com/share?text=<%= @article.title %> by @AdamDebbagh - &amp;url=<%= url_for([@article, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fa fa-twitter"></i></a>
    <!-- Facebook -->
    <a onclick="javascript:window.open('http://www.facebook.com/sharer.php?u=<%= url_for([@article, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fa fa-facebook"></i></a>
    <!-- Google Plus -->
    <a onclick="javascript:window.open('https://plus.google.com/share?url=<%= url_for([@article, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fa fa-google-plus"></i></a>
  </div>
  <hr>
  <%= render 'articles/disqus'%>
</div>

app/views/contacts/create.html.erb
<h1 id="page_title">Say, Hello </h1>

<div class="skinny_wrapper wrapper_padding">
  <h1>Thank you for your message!</h1>
  <p>I'll get back to you soon.</p>
</div>

app/views/contacts/new.html.erb
<h1 id="page_title">Say Hello!</h1>

<div class="skinny_wrapper wrapper_padding">
  <%= form_for @contact do |f| %>
      <%= f.label :name %><br>
      <%= f.text_field :name, required: true %>

      <br>

      <%= f.label :email %><br>
      <%= f.email_field :email, required: true %>

      <br>

      <%= f.label :message %><br>
      <%= f.text_area :message, as: :text %>

      <div class="hidden">
        <%= f.label :nickname %><br>
        <%= f.text_field :nickname, hint: 'leave this field blank' %>
      </div>

      <%= f.submit 'Send Message', class: "button" %>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer id="main_footer">
  <p class="copyright">&copy;2015
    <%= link_to 'Adam Debbagh', new_user_session_path, class:'sign_in' %>
  </p>
  <nav>
    <a href="https://twitter.com/AdamDebbagh" target="_blank"><i class="fa fa-twitter"></i></a>
    <a href="https://github.com/Adamdebbagh" target="_blank"><i class="fa fa-github"></i></a>
    <a href="https://www.facebook.com/lhodeb" target="_blank"><i class="fa fa-facebook"></i></a>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header id="main_navigation" class="clearfix">
  <%= link_to 'ADAM DEBBAGH', root_path ,class:'name' %>
  <nav>
    <%= link_to 'Articles', articles_path %>
    <%= link_to 'Projects', projects_path %>
    <%= link_to 'Contact', new_contact_path %>
    <%if user_signed_in? %>
        <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
    <% end %>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ADAM Debbagh - Part Designer, Part Developer</title>
  <link href='//fonts.googleapis.com/css?family=Raleway:400,700' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <%= csrf_meta_tags %>

</head>
<body>
<%= render 'layouts/header' %>

<!--notifications-->
<% if notice %>
    <p class="notice"><%= notice %></p>
<% elsif alert %>
    <p class="alert"><%= alert %></p>
<% end %>
<%= yield %>
<%= render 'layouts/footer'%>
</body>
</html>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
    <% if @project.errors.any? %>
        <h2><%= pluralize(@project.count,"error")%> prevented this project from saving:</h2>
        <ul>
          <% @project.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
          <% end %>
        </ul>
    <% end %>

    <%= f.label :title%><br>
    <%= f.text_field :title%>
    <br><br>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
    <br><br>
    <%= f.label :link %><br>
    <%= f.text_field :link %>
    <br><br>
    <%= f.submit %>
<% end%>

app/views/projects/edit.html.erb
<div class="wrapper_padding skinny_wrapper">
  <h1 id="page_title">Edit Project</h1>
  <%= render 'projects/form'%>
</div>

app/views/projects/index.html.erb
<h1 id="page_title">Projects i've built
  <br><br>
  <span class="new_button">
   <% if user_signed_in? %>
      <%= link_to 'New Project', new_project_path %>
   <% end %>
  </span>
</h1>

<div id="post_wrapper" class="skinny_wrapper">
  <% @projects.each do |project| %>
      <div class="post">
        <p class="date"><%= project.created_at.strftime('%A, %b %d')%></p>
        <h2><%= link_to project.title, project %></h2>
        <hr>
      </div>
  <% end%>
</div>
<%#= will_paginate @articles %>

app/views/projects/new.html.erb
<div class="wrapper_padding skinny_wrapper">
  <h1 id="page_title">New Project</h1>
  <%= render 'projects/form'%>
</div>

app/views/projects/show.html.erb
<div id="post_show_content" class="skinny_wrapper wrapper_padding">
  <header>
    <p class="date"><%= @project.created_at.strftime( ' %A' ' %b' ' %d') %></p>
    <h1><%= @project.title %></h1>



    <hr>
  </header>

  <div id="content">
    <% author = ' Developed By Adam Debbagh'%>
    <h6><%= author %></h6>
    <p><%= simple_format @project.description %></p>
    <div class="button_wrapper">
        <a href="<%=  @project.link%>"  target="_blank" class="button_link" >Visit <%= @project.title %></a>
    </div>
    <% if user_signed_in? %>
        <div id="admin_links">
          <%= link_to 'edit', edit_project_path(@project) %>
          <%= link_to 'delete', project_path(@project), method: :delete, data: {
                                      confirm: "Are you sure you want to delete this post?"
                              } %>
        </div>
    <% end %>
  </div>
  <hr>
</div>

app/views/welcome/index.html.erb
<div class="wrapper wrapper_padding clearfix">
  <div class="col-1 about homepage_content" >
    <section>
        <h2>About</h2>
        <p>I'm a designer &amp; developer living in Washington dc Area.</p>
        <p>Quickly revolutionize emerging communities rather than just in time internal or "organic" sources. <a href="#">Dynamically</a> disseminate covalent relationships before state of the art expertise. Conveniently drive customer directed value via go forward niches. </p>
        <p>Quickly revolutionize emerging communities rather than just in time internal or "organic" sources. Dynamically disseminate covalent relationships before</p>
    </section>
  </div>
</div>
<div class="wrapper clearfix">
  <div class="col-2 homepage_content" >
    <aside>
        <h2>Latest Articles</h2>
        <% @articles.each do |article|%>
            <h3><%= link_to article.title, article %></h3>
            <p class="date"><%= article.created_at.strftime('%A' ' %b' ' %d')  %></p>
        <% end %>
    </aside>
  </div>
</div>
<div class="wrapper wrapper_padding clearfix">
  <div class="col-3 homepage_content">
    <aside>
        <h2>Latest Projects</h2>

        <% @projects.each do |project|%>
            <h3><%= link_to project.title, project %></h3>
            <p class="date"><%= project.created_at.strftime('%A, %b %d')  %></p>
        <% end %>
    </aside>

</div>
</div>